name: sentry-notifier-lambda-ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle with caching
        uses: gradle/actions/setup-gradle@v3

      - name: Create .env file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DOTENV_FILE }}" > src/main/resources/.env

      - name: Compile and run test
        run: |
          ./gradlew check
